[package]
name = "attendance-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.7",  features = ["r2d2", "postgres", "chrono"] }
dotenvy = "0.15.7"
env_logger = "0.11.6"
serenity = "0.12.4"
tokio = { version = "1.43.0", features = ["full"] }
